### ISSUE TITLE
怎么使用同一渠道不同群的消息发送

### ISSUE THREAD

**Issue by hh-Ink** [VinchanGit/message-notice#2]
需求：
现在有两个企业微信群。一个群是用来做日志收集的，错误日志发到这个群。一个群（会有多个）是来做业务通知运营的，某个特定的业务变更要通知这个群
问题：
按照配置文件及driver对配置文件的获取处理，只支持一个driver对应一个key。如果有多个群就需要有多个驱动类，需要使用者知己实现，后期不利于维护。
建议：
是否可以在配置文件中为每个 channels 增加一个 driver 配置，key从外部传入

**Comment by phptoken** [comment]
非常棒的，这个功能已经在增加啦，打算在2.0的时候发布。

**Comment by VinchanGit** [comment]
很棒，这个功能已经在做啦，打算在下个版本发布。
